### ISSUE TITLE
Deploy script failing for me

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#116]
I tried to deploy this a few times and failed, though deploy has worked for me in the distant past (2+ years ago).

In this case, I even blew away all my local code and started fresh from scratch following our README https://github.com/GreenInfo-Network/seattle-building-dashboard?tab=readme-ov-file#how-do-i-install-it instructions for install and deploy.

Each time I get the same error at the bottom of the output below. Not sure yet what the cause is.

```zsh
% nvm use
...
Now using node v18.12.1 (npm v8.19.2)
% npm install
...
added 1152 packages, and audited 1153 packages in 26s

% bower install
...

% npm run deploy

> cityenergy@1.0.0 deploy
> npm run dist && gulp deploy


> cityenergy@1.0.0 dist
> npm run clean && gulp


> cityenergy@1.0.0 clean
> rm -rf dist/

[10:52:50] Using gulpfile ~/Documents/GINlocalcode/seattle-building-dashboard/gulpfile.js
[10:52:50] Starting 'default'...
[10:52:50] Starting 'clean'...
[10:52:50] Finished 'clean' after 4.3 ms
[10:52:50] Starting 'fileinclude'...
[10:52:50] Finished 'fileinclude' after 27 ms
[10:52:50] Starting 'styles'...
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
[10:52:51] gulp-autoprefixer:
  autoprefixer: /Users/danrademacher/Documents/GINlocalcode/seattle-building-dashboard/src/styles/main.css:4730:5: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
[10:52:51] Finished 'styles' after 1.11 s
[10:52:51] Starting 'scripts'...
[10:52:53] Finished 'scripts' after 1.74 s
[10:52:53] Starting 'images'...
[10:52:53] Finished 'images' after 93 ms
[10:52:53] Starting 'data'...
[10:52:53] Finished 'data' after 7.14 ms
[10:52:53] Starting 'templates'...
[10:52:53] Finished 'templates' after 46 ms
[10:52:53] Starting 'cities_config'...
[10:52:53] Finished 'cities_config' after 15 ms
[10:52:53] Starting 'copy-lib'...
[10:52:53] Finished 'copy-lib' after 31 ms
[10:52:53] Finished 'default' after 3.08 s
[10:52:55] Using gulpfile ~/Documents/GINlocalcode/seattle-building-dashboard/gulpfile.js
[10:52:55] Starting 'deploy'...
[10:52:57] 'deploy' errored after 1.15 s
[10:52:57] TypeError: Cannot read properties of null (reading '0')
    at module.exports.Commit.actor (/Users/danrademacher/Documents/GINlocalcode/seattle-building-dashboard/node_modules/gift/lib/commit.js:145:56)
    at module.exports.Commit.parse_commits (/Users/danrademacher/Documents/GINlocalcode/seattle-building-dashboard/node_modules/gift/lib/commit.js:111:21)
    at /Users/danrademacher/Documents/GINlocalcode/seattle-building-dashboard/node_modules/gift/lib/commit.js:71:39
    at ChildProcess.exithandler (node:child_process:404:7)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:552:15)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:552:15)
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1208066648242756)

**Comment by tomay** [comment]
it has worked fine for me recently on a fresh install from ~6 mo ago. 

Unfortunately, this is an error stemming from a 13 year old node package... 

Looks similar to this: 
https://stackoverflow.com/questions/47211594/gulp-gh-pages-not-working

And to some extent this: https://github.com/shower/shower/issues/318 (we are also using `gulp-gh-pages` here)

In `package-lock.json` I see that we have `gift` version 0.6.1, so possibly that "resolutions" block fix from SO would help get a more recent version
